AWSTemplateFormatVersion: "2010-09-09"
Description: 
  "Create ECR repository."

Parameters:
  EcrRepoName:
    Type: "String"
    Description: "Enter the name of the ECR Repository."
    Default: "sample-repository"

# ECSで実行するDockerイメージを格納するECRを作成する
Resources:
  LambdaEcrRepository:
    Type: "AWS::ECR::Repository"
    Properties:
      RepositoryName: !Ref "EcrRepoName"
